version: "3.7"

services:
  sidecar:
    build:
      context: ./sidecar
    image: sidecar:latest
    ports:
      - 8080:8080
    volumes:
      - ./port.sh:/port.sh
      - /var/run/docker.sock:/var/run/docker.sock

  bee:
    build:
      context: ./bee
    image: bee-scale:latest
    environment:
      - BEE_PASSWORD=changeme
      - BEE_SWAP_ENDPOINT=https://xdai.fairdatasociety.org
      - BEE_DB_OPEN_FILES_LIMIT=1000
      - BEE_FULL_NODE=true
      - BEE_DEBUG_API_ENABLE=true
    ports:
      - "36330-36339:1633"
      - "32001-32010:1634"
      - "36350-36359:1635"
    restart: "unless-stopped" 
    depends_on: 
      - sidecar
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '2'
          memory: 4G
    logging:
      driver: "json-file"
      options:
        max-file: "5"   # number of files or file count
        max-size: "10m" # file size
